// Generated by gencpp from file my_turtle/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MY_TURTLE_MESSAGE_ADDTWOINTS_H
#define MY_TURTLE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <my_turtle/AddTwoIntsRequest.h>
#include <my_turtle/AddTwoIntsResponse.h>


namespace my_turtle
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace my_turtle


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_turtle::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::my_turtle::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::my_turtle::AddTwoInts > {
  static const char* value()
  {
    return "my_turtle/AddTwoInts";
  }

  static const char* value(const ::my_turtle::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::my_turtle::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::my_turtle::AddTwoInts >
template<>
struct MD5Sum< ::my_turtle::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_turtle::AddTwoInts >::value();
  }
  static const char* value(const ::my_turtle::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_turtle::AddTwoIntsRequest> should match
// service_traits::DataType< ::my_turtle::AddTwoInts >
template<>
struct DataType< ::my_turtle::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::my_turtle::AddTwoInts >::value();
  }
  static const char* value(const ::my_turtle::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_turtle::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::my_turtle::AddTwoInts >
template<>
struct MD5Sum< ::my_turtle::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_turtle::AddTwoInts >::value();
  }
  static const char* value(const ::my_turtle::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_turtle::AddTwoIntsResponse> should match
// service_traits::DataType< ::my_turtle::AddTwoInts >
template<>
struct DataType< ::my_turtle::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::my_turtle::AddTwoInts >::value();
  }
  static const char* value(const ::my_turtle::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_TURTLE_MESSAGE_ADDTWOINTS_H
